version: "3.9"

volumes:
  postgre_data:
  static_volume:
  media_volume:

services:
  app:
    image: app_image
    container_name: app
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app/
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  celery:
    image: app_image
    container_name: app_celery
    command: celery -A django_admin_array_files_upload worker -l INFO
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - app
      - redis

  redis:
    image: redis:7.0.1-alpine
    container_name: app_redis
    restart: always

  db:
    image: postgres:15.2-alpine
    container_name: app_db
    restart: always
    volumes:
      - postgre_data:/var/lib/postgresql/data
    env_file:
      - .env

  nginx:
    image: nginx:1.23.4-alpine
    container_name: app_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
