# Generated by Django 4.1 on 2023-07-27 09:22

import app.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithFilesArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=app.utils.upload_files_path), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Объект с массивом файлов',
                'verbose_name_plural': 'Объекты с массивами файлов',
            },
        ),
        migrations.CreateModel(
            name='ModelWithImagesArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=app.utils.upload_files_path), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Объект с массивом изображений',
                'verbose_name_plural': 'Объекты с массивами изображений',
            },
        ),
    ]
