# Generated by Django 4.1 on 2023-08-20 16:23

import app.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilesarray',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=app.utils.upload_files_path), blank=True, default=list, null=True, size=None, verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='modelwithimagesarray',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=app.utils.upload_files_path), blank=True, default=list, null=True, size=None, verbose_name='Изображения'),
        ),
    ]
